---
# this could be refactored for normal user mode
- name: 'install required RPMs'
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ perl_rpms }}"
  tags:
    - perl
    - perl_rpms

- name: 'ensure CPAN config exists'
  become: yes
  file:
    path: '/root/.cpan/CPAN/'
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - perl
    - perl_config

- name: 'install CPAN configuration'
  become: yes
  template:
    src: 'MyConfig.pm'
    dest: '/root/.cpan/CPAN/'
  tags:
    - perl
    - perl_config

# Dirty yes.
- name: 'installing CPANM'
  become: yes
  shell: 'curl -L https://cpanmin.us | perl - App::cpanminus'
  tags:
    - perl

# Perl modules with Ansible
- name: 'install optional modules'
  environment:
    PATH: '/sbin:/usr/sbin/:bin:/usr/bin:/usr/local/bin'
  cpanm:
    name: "{{ item }}"
  with_items: "{{ perl_modules}}"
  tags:
    - perl
    - perl_modules
